version: '3'
services:
  web:
    build: .
    image: ${COOLIFY_IMAGE_NAME}
    ports:
      - "${PORT}:8000"
    environment:
      DJANGO_SETTINGS_MODULE: membership_comparison.settings
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: 0
      ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DATABASE_URL: postgres://era:Era.151081@fgkck480gogo88o40ko8cs0s:5432/membership_db
    networks:
      - coolify
    volumes:
      - staticfiles:/app/staticfiles

networks:
  coolify:
    external: true
    name: coolify

volumes:
  staticfiles:
