# Generated by Django 5.1.3 on 2024-11-14 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('file_content', models.BinaryField()),
            ],
            options={
                'ordering': ['-year', '-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('cell', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(max_length=20)),
                ('mandate_signed', models.CharField(max_length=50)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.membershipupload')),
            ],
            options={
                'indexes': [models.Index(fields=['cell'], name='reports_mem_cell_7f7e03_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComparisonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('new_active_members', models.JSONField(default=list)),
                ('new_free_members', models.JSONField(default=list)),
                ('new_linked_members', models.JSONField(default=list)),
                ('new_leads', models.JSONField(default=list)),
                ('cancelled_members', models.JSONField(default=list)),
                ('status_changes', models.JSONField(default=list)),
                ('removed_members', models.JSONField(default=list)),
                ('current_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_reports', to='reports.membershipupload')),
                ('previous_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_reports', to='reports.membershipupload')),
            ],
            options={
                'ordering': ['-generated_date'],
                'unique_together': {('current_upload', 'previous_upload')},
            },
        ),
    ]
